name: Test & Release
on:
  pull_request:
  push:
    tags:
        - v*
    branches:
      - main
jobs:
  create_release:
    # if: contains(github.ref, '/tags/v')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.12','3.13']
    steps:
        - uses: actions/checkout@v4
        - name: Get tag version
          id: tag_name
          run: | 
            echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
            echo "SOURCE_TAG is set to: $SOURCE_TAG"