name: Test & Release
on:
  pull_request:
  push:
    tags:
        - v*
    branches:
      - main
      - GESDISCUMU-5118-migrate-gap-dection-codebase-and-template
jobs:
  create_release:
    # needs: build
    # if: contains(github.ref, '/tags/v')
    runs-on: ubuntu-latest
    steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Run packaging script
            run: ./package_lambdas_and_layers